### ISSUE TITLE
Disable thumbnail generation

### ISSUE THREAD

**Issue by starkgate** [Lawrr/Japanese-To-Romaji-Filename-Converter#1]
It would be nice to have an option to disable thumbnail generation. I wanted to rename about 9000 files, and found that 1.1 was much faster than 1.2, since it simply didn't spend time on thumbnails.

**Comment by Lawrr** [comment]
Took a while but this issue should be fixed now and the load speeds should now be about the same as v1.1 with no visible impact to performance, even with the thumbnails present. As of v1.4.0 (https://github.com/Lawrr/Japanese-To-Romaji-Filename-Converter/commit/bc055ccec0437208f69a9a0874999c709203a060, https://github.com/Lawrr/Japanese-To-Romaji-Filename-Converter/commit/17b9cdfb4b539c96e6a869918925bed1de8a3ef0).

**Comment by CreeperLava** [comment]
Thank you !
