### ISSUE TITLE
Strange Error with jpg and log

### ISSUE THREAD

**Issue by ghost** [Lawrr/Japanese-To-Romaji-Filename-Converter#2]
In the attachment are 2 files. A `jpg`-file and a `log`-file. The following problems occurs for me:

Version 1.2 throws an exception for the jpg and therefor the process of renaming aborts.
Version 1.1 and 1.0 don't throw one, but they do with the log file.

I tested that on 2 diffrent Windows 10 machines. It's quite annoying, since it stops the process of renaming.
[Test Romaji Generator.zip](https://github.com/Lawrr/Japanese-To-Romaji-Filename-Converter/files/1032579/Test.Romaji.Generator.zip)

**Comment by Lawrr** [comment]
Thanks for the report. This has been fixed and should work in v.1.3 once I release it in a couple of days.
