### ISSUE TITLE
ノ keeps getting translated to " A " (space A space) and editing the maps doesn't work

### ISSUE THREAD

**Issue by g4269159** [Lawrr/Japanese-To-Romaji-Filename-Converter#4]
Do you know how to fix this?

**Comment by g4269159** [comment]
example:
Converted: 「桜前線異常ナシ」を歌って弾いてみた【杏ノ助×530】 - YouTube.MP4 to 「Sakurazensen Ijō Nashi」 o Utatte Hiitemita 【 Anzu A Suke ×530】 - YouTube.MP4

Converted: 【なつうた】 11 悪ノ召使【合唱】 - Niconico Video_GINZA.mp4 to 【 Natsu Uta 】 11 Waru A Meshitsukai 【 Gasshō 】 - Niconico Video_GINZA.mp4

**Comment by g4269159** [comment]
current kana map:
 ̄ : 
eye:ai
lung:rune
ryer:liar
re oru:reol
coco palm:kokoyashi
Sando Lyon:Cendrillon
hibikashi:hibikase
Pear:nashi
 A :no

**Comment by Lawrr** [comment]
Kana map with `A:no` (no spaces) should work. Let me know if that still doesn't work.

**Comment by g4269159** [comment]
I see so spaces were the issue, but this causes A that aren't ノ to get converted such as  Sakurazensen Ijō Nnoshi (properly "Sakurazensen Ijō Nashi") so I think I will just let it be.

**Comment by Lawrr** [comment]
Ah yes, I forgot about that. In that case, the mappings support regular expressions, so you can use `\bA\b:no` so that that it'll only get converted if the whole word is "A".

**Comment by g4269159** [comment]
That worked perfectly thank you so much!!

**Comment by Lawrr** [comment]
Glad I could help.
