### ISSUE TITLE
Sokuon transliterating as normal kana?

### ISSUE THREAD

**Issue by g4269159** [Lawrr/Japanese-To-Romaji-Filename-Converter#5]
Turrira:Chururira
Dudadda:Daddadda
Guasshiyu:Guasshu

Do you have a map that would fix this in all circumstances? I'm only going off of full mistransliterated words.

**Comment by Lawrr** [comment]
Sorry, I don't quite get the question. Could you elaborate?

**Comment by g4269159** [comment]
Is there a way to fix sokuon transliterating as normal kana symbols, since as of now it's malfunctioning
for example ぐあっしゅ ＝＞ should be transliterated as Guasshu, but transliterates as Guasshiyu due to the しゅ being treated as しゆ。

**Comment by Lawrr** [comment]
I don't think there's a map to fix that, but I'll look into fixing it. Hopefully I'll have time in a couple of days.

**Comment by Lawrr** [comment]
This should be fixed now as of v1.4.0  (https://github.com/Lawrr/Japanese-To-Romaji-Filename-Converter/commit/f94a1502cae137a8c53420a98954fea6fa570073, https://github.com/Lawrr/Japanese-To-Romaji-Filename-Converter/commit/2d72ee12294b023fe49216ca6ef82c49a696a08b). Let me know if you still experience the problem.
